blank_issues_enabled: false
contact_links:
  - name: Lexi.new Help Center
    url: https://support.lexi.new
    about: Official central repository for tips, tricks, tutorials, known issues, and best practices for lexi.new usage.
  - name: Billing Issues
    url: https://support.lexi.new/Billing-13fd971055d680ebb393cb80973710b6
    about: Instructions for billing and subscription related support
  - name: Discord Chat
    url: https://discord.gg/stackblitz
    about: Build, share, and learn with other Lexiers in real time.
